// Trabajo Practico 4/trabajo-practico-4-react/src/components/ProductCard.js
import React, { Component } from "react";
import Card from "react-bootstrap/Card";
import ShippingCost from "./ShippingCost";

class ProductCard extends Component {
  render() {
    return (
      <React.Fragment>
        <Card className="tarjeta">
          <Card.Body className="body">
            <a href={`product-details/${this.props.id}`}>
              <img
                className="imagen mr-4"
                src={require(`../images/${this.props.imagen}`)}
                alt="Imagen del Producto"
                align="left"
              />
            </a>
            <a href={`product-details/${this.props.id}`}>
              <Card.Title className="title" >{this.props.nombre}</Card.Title>
            </a>
            <Card.Text className="price" >${this.props.precio}</Card.Text>
            <ShippingCost costoEnvio={this.props.costoEnvio}></ShippingCost>
            <Card.Text className="sold mt-2" >{this.props.cantidadVendida} Vendidos</Card.Text>
          </Card.Body>
        </Card>
      </React.Fragment>
    );
  }
}

export default ProductCard;

// Trabajo Practico 6/trabajo-practico-6-vue/src/components/ProductCard.vue
<template>
  <router-link :to="{ name: 'Product Details', params: { id: instrumento.id }}">
    <b-card
      :img-src="require('../assets/images/' + instrumento.imagen)"
      :img-alt="instrumento.id"
      img-left
      class="mb-3 img-list"
    >
      <b-card-title class="font-weight-light">{{ instrumento.instrumento }}</b-card-title>
      <b-card-title>{{ instrumento.precio | currency }}</b-card-title>
      <shipping-cost :cost="instrumento.costoEnvio"></shipping-cost>
      <small class="text-muted">{{ instrumento.cantidadVendida }} Vendidos.</small>
    </b-card>
  </router-link>
</template>

<script>
import ShippingCost from "@/components/ShippingCost.vue";

export default {
  name: "product-card",
  components: {
    "shipping-cost": ShippingCost
  },
  props: {
    instrumento: Object
  }
};
</script>

<style scoped>
a {
  color: black;
}

a:hover {
  text-decoration: none !important;
}
</style>
