// Trabajo Practico 4/trabajo-practico-4-react/src/components/ShippingCost.js
import React, { Component } from "react";

class ShippingCost extends Component {
  render() {

    if (this.props.costoEnvio === "G") {
      this.shipping = (
        <span className="free-shipping">
          <img
            src={require(`../images/camion.png`)}
            alt="envio gratis"
          ></img>
          Envío gratis a todo el País
        </span>
      );
    } else {
      this.shipping = (
        <span className="shipping-cost">
          Costo de Envío Interior de Argentina: ${this.props.costoEnvio}
        </span>
      );
    }

    return (
      <div>
       {this.shipping}
      </div>
    );
  }
}

export default ShippingCost;

// Trabajo Practico 6/trabajo-practico-6-vue/src/components/ShippingCost.vue
<template>
  <div>
    <span v-if="cost === 'G'" class="free-shipping">
      <img src="../assets/images/camion.png" />
      <small>Envío gratis a todo el País</small>
    </span>
    <span v-else class="shipping-cost">
      <small>Costo de Envío Interior de Argentina: {{ cost | currency }}</small>
    </span>
  </div>
</template>

<script>
export default {
  name: "shipping-cost",
  props: {
    cost: String
  }
};
</script>

<style>
.free-shipping {
  color: green;
}

.shipping-cost {
  color: orangered;
}
</style>
