// Trabajo Practico 4/trabajo-practico-4-react/src/pages/Home.js
import React from "react";
import Toolbar from "../components/Toolbar";
import { Row, Container, Col } from "react-bootstrap";

const Home = () => (
  <React.Fragment>
    <Toolbar></Toolbar>
    <Container className="mt-5">
      <Row>
        <Col>
          <h1>Musical Hendrix</h1>
          <p>Musical Hendrix es una tienda de instrumentos musicales con ya más de 15 años de experiencia. Tenemos el
          conocimiento y la capacidad como para informarte acerca de las mejores elecciones para tu compra musical.</p>
        </Col>
      </Row>
    </Container>
  </React.Fragment>
);

export default Home;

// Trabajo Practico 6/trabajo-practico-6-vue/src/views/Home.vue
<template>
  <div>
    <b-jumbotron
      header="Musical Hendrix"
      lead="Musical Hendrix es una tienda de instrumentos musicales con ya más de 15 años de experiencia. Tenemos el
      conocimiento y la capacidad como para informarte acerca de las mejores elecciones para tu compra musical."
    >
      <b-button variant="primary" href="/product-list">Productos</b-button>
    </b-jumbotron>
  </div>
</template>
