// Trabajo Practico 4/trabajo-practico-4-react/src/pages/ProductList.js
import React, { Component } from "react";
import { Col, Container } from "react-bootstrap";
import { instrumentos } from "../data/instrumentos.json";
import Toolbar from "../components/Toolbar";
import ProductCard from "../components/ProductCard";
import Breadcrumb from 'react-bootstrap/Breadcrumb'

class ProductList extends Component {
  constructor() {
    super();
    this.state = { instrumentos };
  }

  render() {
    const instrumentos = this.state.instrumentos.map((instrumento, i) => {
      return (
        <ProductCard
          key={instrumento.id}
          id={instrumento.id}
          nombre={instrumento.instrumento}
          marca={instrumento.marca}
          modelo={instrumento.modelo}
          imagen={instrumento.imagen}
          precio={instrumento.precio}
          costoEnvio={instrumento.costoEnvio}
          cantidadVendida={instrumento.cantidadVendida}
          descripcion={instrumento.descripcion}
        ></ProductCard>
      );
    });
    return (
      <React.Fragment>
        <Toolbar></Toolbar>
        <Breadcrumb>
          <Breadcrumb.Item href="/home">Home</Breadcrumb.Item>
          <Breadcrumb.Item active>Productos</Breadcrumb.Item>
        </Breadcrumb>
        <Container className="container mt-5">
          <h1 className="mb-4 ml-3">Listado de productos</h1>
          <Col>{instrumentos}</Col>
        </Container>
      </React.Fragment>
    );
  }
}

export default ProductList;

// Trabajo Practico 6/trabajo-practico-6-vue/src/views/ProductList.vue
<template>
  <div>
    <div>
      <b-breadcrumb :items="items"></b-breadcrumb>
    </div>
    <div>
      <div class="container mt-5">
        <h1>Productos</h1>
        <div v-for="instrumento in instrumentos" :key="instrumento.id">
          <product-card :instrumento="instrumento"></product-card>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import ProductCard from "@/components/ProductCard.vue";
import Json from "../data/instrumentos.json";

export default {
  name: "ProductList",
  components: {
    "product-card": ProductCard
  },
  data() {
    return {
      instrumentos: Json.instrumentos,
      items: [
        {
          text: "Home",
          href: "/"
        },
        {
          text: "Productos",
          active: true
        }
      ]
    };
  }
};
</script>
