// Trabajo Practico 6/trabajo-practico-6-vue/src/components/ShippingCost.vue
<template>
  <div>
    <span v-if="cost === 'G'" class="free-shipping">
      <img src="../assets/images/camion.png" />
      <small>Envío gratis a todo el País</small>
    </span>
    <span v-else class="shipping-cost">
      <small>Costo de Envío Interior de Argentina: {{ cost | currency }}</small>
    </span>
  </div>
</template>

<script>
export default {
  name: "shipping-cost",
  props: {
    cost: String
  }
};
</script>

<style>
.free-shipping {
  color: green;
}

.shipping-cost {
  color: orangered;
}
</style>

// Trabajo Practico 8/trabajo-practico-8-angular/src/app/components/shipping-cost/shipping-cost.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-shipping-cost',
  templateUrl: './shipping-cost.component.html',
  styleUrls: ['./shipping-cost.component.scss']
})
export class ShippingCostComponent implements OnInit {

  @Input()
  public cost: any;

  constructor() { }

  ngOnInit(): void {
  }

}

<div *ngIf="cost === 'G'; then freeShipping else shippingCost"></div>
<ng-template #freeShipping>
  <span class="free-shipping">
    <img src="assets/images/camion.png" />
    <small>Envío gratis a todo el País</small>
  </span>
</ng-template>
<ng-template #shippingCost>
  <span class="shipping-cost">
    <small>Costo de Envío Interior de Argentina: {{ cost | currency }}</small>
  </span>
</ng-template>
