// Trabajo Practico 9/trabajo-practico-9-angular/src/app/components/product-card/product-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Instrumento } from 'src/app/shared/models/instrumento';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss']
})
export class ProductCardComponent implements OnInit {

  @Input()
  public data: Instrumento;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card w-100 mb-3">
  <div class="row no-gutters">
    <div class="col-md-2">
      <img [src]="'http://localhost:8080/api/v1/instrumentos/images/' + data.imagen" [alt]="data.instrumento"
        class="card-img">
    </div>
    <div class="col-md-10">
      <div class="card-body">
        <h3 class="card-title font-weight-light"> {{ data.instrumento }} </h3>
        <h3 class="card-title"> {{ data.precio | currency }} </h3>
        <app-shipping-cost [data]="data.costoEnvio"></app-shipping-cost>
        <p class="card-text"><small class="text-muted">{{ data.cantidadVendida }} Vendidos.</small></p>
      </div>
    </div>
  </div>
</div>

// Trabajo Practico 7/trabajo-practico-7-vue/src/components/ProductCard.vue
<template>
  <router-link :to="{ name: 'Product Details', params: { id: instrumento.id }}">
    <b-card
      :img-src="'http://localhost:8080/api/v1/instrumentos/images/' + instrumento.imagen"
      :img-alt="instrumento.instrumento"
      img-left
      class="mb-3"
    >
      <b-card-title class="font-weight-light">{{ instrumento.instrumento }}</b-card-title>
      <b-card-title>{{ instrumento.precio | currency }}</b-card-title>
      <shipping-cost :cost="instrumento.costoEnvio"></shipping-cost>
      <small class="text-muted">{{ instrumento.cantidadVendida }} Vendidos.</small>
    </b-card>
  </router-link>
</template>

<script>
import ShippingCost from "@/components/ShippingCost.vue";

export default {
  name: "product-card",
  components: {
    "shipping-cost": ShippingCost
  },
  props: {
    instrumento: Object
  }
};
</script>

<style scoped>
img {
  min-height: 160px;
  min-width: 160px;
  max-height: 160px;
  max-width: 160px;
}

a {
  color: black;
}

a:hover {
  text-decoration: none !important;
}
</style>
