// Trabajo Practico 6/trabajo-practico-6-vue/src/components/ProductCard.vue
<template>
  <router-link :to="{ name: 'Product Details', params: { id: instrumento.id }}">
    <b-card
      :img-src="require('../assets/images/' + instrumento.imagen)"
      :img-alt="instrumento.id"
      img-left
      class="mb-3 img-list"
    >
      <b-card-title class="font-weight-light">{{ instrumento.instrumento }}</b-card-title>
      <b-card-title>{{ instrumento.precio | currency }}</b-card-title>
      <shipping-cost :cost="instrumento.costoEnvio"></shipping-cost>
      <small class="text-muted">{{ instrumento.cantidadVendida }} Vendidos.</small>
    </b-card>
  </router-link>
</template>

<script>
import ShippingCost from "@/components/ShippingCost.vue";

export default {
  name: "product-card",
  components: {
    "shipping-cost": ShippingCost
  },
  props: {
    instrumento: Object
  }
};
</script>

<style scoped>
a {
  color: black;
}

a:hover {
  text-decoration: none !important;
}
</style>

// Trabajo Practico 8/trabajo-practico-8-angular/src/app/components/product-card/product-card.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Instrumento } from 'src/app/shared/models/instrumento';

@Component({
  selector: 'app-product-card',
  templateUrl: './product-card.component.html',
  styleUrls: ['./product-card.component.scss']
})
export class ProductCardComponent implements OnInit {

  @Input()
  public instrumento: Instrumento;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="pb-3">
  <mat-card [routerLink]="['/product-details', instrumento.id]">
    <div class="row">
      <div class="col-4 col-md-4 col-lg-2">
        <img src="assets/images/{{instrumento.imagen}}">
      </div>
      <div class="col-8 col-md-8 col-lg-10">
        <mat-card-content>
          <h1 class="font-weight-light"> {{ instrumento.instrumento }} </h1>
          <mat-card-title>{{ instrumento.precio | currency }}</mat-card-title>
          <app-shipping-cost [cost]="instrumento.costoEnvio"></app-shipping-cost>
          <br>
          <span class="text-muted"> {{ instrumento.cantidadVendida }} Vendidos.</span>
        </mat-card-content>
      </div>
    </div>
  </mat-card>
</div>
