// Trabajo Practico 6/trabajo-practico-6-vue/src/views/ProductDetails.vue
<template>
  <div>
    <b-breadcrumb>
      <b-breadcrumb-item href="/">Home</b-breadcrumb-item>
      <b-breadcrumb-item href="/product-list">Productos</b-breadcrumb-item>
      <b-breadcrumb-item active>{{ instrumento.instrumento }}</b-breadcrumb-item>
    </b-breadcrumb>
    <b-container class="mt-5">
      <b-row>
        <b-col cols="8">
          <img
            :src="require('../assets/images/' + instrumento.imagen)"
            :img-alt="instrumento.id"
            class="img-details"
          />
          <br />
          <small>{{ instrumento.descripcion }}</small>
        </b-col>
        <b-col>
          <small class="text-muted">{{ instrumento.cantidadVendida }} vendidos</small>
          <h3>{{ instrumento.instrumento }}</h3>
          <h1 class="font-weight-light">{{ instrumento.precio | currency }}</h1>
          <small class="font-weight-bold">Marca: {{ instrumento.marca }}</small>
          <br />
          <small class="font-weight-bold">Modelo: {{ instrumento.modelo }}</small>
          <br />
          <br />
          <small>Costo Envio:</small>
          <shipping-cost :cost="instrumento.costoEnvio"></shipping-cost>
          <br />
          <b-button variant="outline-primary">Agregar al carrito</b-button>
        </b-col>
      </b-row>
    </b-container>
  </div>
</template>

<script>
import ShippingCost from "@/components/ShippingCost.vue";
import Json from "../data/instrumentos.json";

export default {
  name: "ProductDetails",
  components: {
    "shipping-cost": ShippingCost
  },
  data() {
    return {
      instrumento: Json.instrumentos[this.$route.params.id - 1]
    };
  }
};
</script>

<style scoped>
.img-details {
  min-height: 100%;
  max-height: 100%;
  max-width: 100%;
  width: auto;
  display: flex;
  margin: 0 auto;
}
</style>

// Trabajo Practico 4/trabajo-practico-4-react/src/pages/ProductDetails.js
import React, { Component } from "react";
import { instrumentos } from "../data/instrumentos.json";
import Toolbar from "../components/Toolbar";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Breadcrumb from 'react-bootstrap/Breadcrumb'
import ShippingCost from '../components/ShippingCost'

class ProductDetails extends Component {

  constructor() {
    super();
    this.state = { instrumentos };
  }

  render() {
    const id = this.props.match.params.id;
    const instrumento = instrumentos.filter(
      (instrumento) => instrumento.id === id
    )[0];

    return (
      <React.Fragment>
        <Toolbar></Toolbar>
        <Breadcrumb>
          <Breadcrumb.Item href="/home">Home</Breadcrumb.Item>
          <Breadcrumb.Item href="/product-list">Productos</Breadcrumb.Item>
          <Breadcrumb.Item active>{instrumento.instrumento}</Breadcrumb.Item>
        </Breadcrumb>
        <Container className="container mt-5">
          <Row>
            <Col>
              <img
                src={require(`../images/${instrumento.imagen}`)}
                alt="Imagen producto"
                className="img-details"
              ></img>
              <div className="descripcion">
                <h5>Descipción</h5>
                <p>{instrumento.descripcion}</p>
              </div>
            </Col>
            <Col >
              <p className="sold">
                {instrumento.cantidadVendida} vendidos
              </p>
              <h3>{instrumento.instrumento}</h3>
              <h2 className="price-details">${instrumento.precio}</h2>
              <br></br>
              <h6 className="font-weight-bold">Marca: {instrumento.marca}</h6>
              <h6 className="font-weight-bold">Modelo: {instrumento.modelo}</h6>
              <p className="mt-5">Costo envío:</p>
              <ShippingCost costoEnvio={instrumento.costoEnvio}></ShippingCost>
              <br></br>
              <button className="btn btn-outline-primary">Agregar al carrito</button>
            </Col>
          </Row>
        </Container>
      </React.Fragment>
    );
  }
}

export default ProductDetails;
