// Trabajo Practico 9/trabajo-practico-9-angular/src/app/pages/product-table/product-table.component.ts
import { Component, OnInit } from '@angular/core';
import { Instrumento } from 'src/app/shared/models/instrumento';
import { HttpService } from 'src/app/shared/services/http.service';

@Component({
  selector: 'app-product-table',
  templateUrl: './product-table.component.html',
  styleUrls: ['./product-table.component.scss']
})
export class ProductTableComponent implements OnInit {

  public instrumentos: Instrumento[] = [];
  public instrumentoActual: Instrumento = {
    id: 0,
    instrumento: '',
    marca: '',
    modelo: '',
    imagen: '',
    precio: 0,
    costoEnvio: '',
    cantidadVendida: 0,
    descripcion: ''
  };

  constructor(private httpService: HttpService) { }

  ngOnInit() {
    this.getAllInstrumentos();
  }

  getAllInstrumentos(): void {
    this.httpService.getAll().subscribe(data => {
      this.instrumentos = data;
    });
  }

  onUpdate(instrumento: Instrumento): void {
    this.instrumentoActual = Object.assign({}, instrumento);
  }

  onDelete(instrumento: Instrumento): void {
    const opcion = confirm('¿Está seguro que desea eliminar este registro?');
    if (opcion === true) {
      this.httpService.delete(instrumento.id).subscribe(() => {
        alert('El registro fue eliminado');
        this.instrumentos.splice(this.instrumentos.indexOf(instrumento), 1);
      });
    }
  }

}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a routerLink="/home">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Tabla</li>
  </ol>
</nav>
<div class="container mt-5">
  <div class="row mb-4 mt-5">
    <div class="col-xs-12 col-sm-8 col-md-10">
      <h1>Tabla de Instrumentos</h1>
    </div>
    <div class=" col-xs-12 col-sm-4 col-md-2">
      <button type="button" class="btn btn-primary float-right ml-3 btn-block" data-toggle="modal"
        data-target="#modalInstrumento" data-backdrop="static">+ Agregar</button>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Marca</th>
            <th scope="col">Modelo</th>
            <th scope="col">Precio</th>
            <th scope="col">Costo Envio</th>
            <th scope="col">Cant. vendida</th>
            <th scope="col">Acciones</th>
            <th scope="col">&nbsp;</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let instrumento of instrumentos">
            <th scope="row">{{instrumento.id}}</th>
            <td>{{instrumento.instrumento}}</td>
            <td>{{instrumento.marca}}</td>
            <td>{{instrumento.modelo}}</td>
            <td>{{instrumento.precio | currency}}</td>
            <td>{{instrumento.costoEnvio}}</td>
            <td>{{instrumento.cantidadVendida}}</td>
            <td>
              <button type="button" class="btn btn-success" (click)="onUpdate(instrumento)" data-toggle="modal"
                data-target="#modalInstrumento" data-backdrop="static">Actualizar</button>
            </td>
            <td>
              <button type="button" class="btn btn-danger" (click)="onDelete(instrumento)">Eliminar</button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<app-modal [instrumentos]="instrumentos" [instrumentoActual]="instrumentoActual"></app-modal>

// Trabajo Practico 5/trabajo-practico-5-react/src/pages/ProductTable.js
import React, { Component } from "react";
import Toolbar from "../components/Toolbar";
import DataService from "../services/data.service";
import { Container, Col, Row, Button, Table } from "react-bootstrap";
import ProductModal from "../components/ProductModal";
import Breadcrumb from 'react-bootstrap/Breadcrumb'

class ProductTable extends Component {
    constructor() {
        super();
        this.state = {
            instrumentos: [],
            formModalShow: false,
            instrumento: {
                id: 0,
                instrumento: "",
                descripcion: "",
                marca: "",
                modelo: "",
                precio: 0,
                costoEnvio: "",
                cantidadVendida: 0,
                imagen: "",
            },
        };
        this.refreshTable = this.refreshTable.bind(this);
    }

    componentDidMount() {
        this.refreshTable();
    }

    // Método que refresca la tabla
    refreshTable() {
        this.getAllInstrumentos();
    }

    // Método que obtiene los instrumentos por página
    getAllInstrumentos() {
        DataService.getAll()
            .then((response) => {
                this.setState({
                    instrumentos: response.data,
                });
            })
            .catch((e) => {
                console.log(e);
            });
    }

    // Método que elimina un instrumento (DELETE)
    deleteInstrumento(instrumento) {
        DataService.delete(instrumento.id)
            .then((response) => {
                console.log(response.data);
                this.refreshTable();
            })
            .catch((e) => {
                console.log(e);
            });
    }

    render() {
        let formModalClose = () => {
            // Oculto el modal y regreso el instrumento a estado vacío
            this.setState({
                formModalShow: false,
                instrumento: {
                    id: 0,
                    instrumento: "",
                    descripcion: "",
                    marca: "",
                    modelo: "",
                    precio: 0,
                    costoEnvio: "",
                    cantidadVendida: 0,
                    imagen: "",
                },
            });
        };

        return (
            <React.Fragment>
                <Toolbar></Toolbar>
                <Breadcrumb>
                    <Breadcrumb.Item href="/home">Home</Breadcrumb.Item>
                    <Breadcrumb.Item active>Tabla</Breadcrumb.Item>
                </Breadcrumb>
                <Container className="container mt-5">
                    <Row>
                        <Col>
                            <h1>Tabla de Instrumentos</h1>
                        </Col>
                        <Col>
                            <Button
                                variant="primary"
                                className="float-right"
                                onClick={() => this.setState({ formModalShow: true })}>
                                Añadir
                            </Button>
                            <ProductModal
                                show={this.state.formModalShow}
                                onHide={formModalClose}
                                instrumento={this.state.instrumento}
                                afterUpdate={this.refreshTable}
                            />
                        </Col>
                    </Row>
                    <Row>
                        <Table striped bordered hover responsive>
                            <thead>
                                <tr>
                                    <th>Instrumento</th>
                                    <th>Modelo</th>
                                    <th>Precio</th>
                                    <th>Envío</th>
                                    <th>Vendidos</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>

                            <tbody>
                                {this.state.instrumentos.map((row, i) => (
                                    <tr key={row.id}>
                                        <td>{row.instrumento}</td>
                                        <td>{row.modelo}</td>
                                        <td>{row.precio}</td>
                                        <td>{row.costoEnvio}</td>
                                        <td>{row.cantidadVendida}</td>
                                        <td>
                                            <Button variant="success" className="mr-2"
                                                onClick={() => {
                                                    this.setState({
                                                        formModalShow: true,
                                                        instrumento: row,
                                                    });
                                                }}>
                                                Editar
                                                </Button>
                                            <Button variant="danger"
                                                onClick={() => {
                                                    if (window.confirm("Seguro deseas eliminar este instrumento?")) {
                                                        this.deleteInstrumento(row);
                                                    }
                                                }}>
                                                Eliminar
                                                </Button>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </Table>
                    </Row>
                </Container>
            </React.Fragment>
        );
    }
}

export default ProductTable;
