// Trabajo Practico 9/trabajo-practico-9-angular/src/app/pages/product-details/product-details.component.ts
import { Component, OnInit } from '@angular/core';
import { Instrumento } from 'src/app/shared/models/instrumento';
import { HttpService } from 'src/app/shared/services/http.service';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-product-details',
  templateUrl: './product-details.component.html',
  styleUrls: ['./product-details.component.scss']
})
export class ProductDetailsComponent implements OnInit {

  public instrumento: Instrumento = {};

  constructor(
    private httpService: HttpService,
    private activeRoute: ActivatedRoute
  ) { }

  ngOnInit(): void {
    this.activeRoute.params.subscribe(data => {
      if (data.id !== 0) {
        this.getInstrumento(data.id);
      }
    }
    );
  }

  getInstrumento(id: number) {
    this.httpService.getOne(id).subscribe(
      response => {
        this.instrumento = response;
      }, error => {
        console.log(error.message);
      });
  }

}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a routerLink="/home">Home</a></li>
    <li class="breadcrumb-item"><a routerLink="/product-list">Productos</a></li>
    <li class="breadcrumb-item active" aria-current="page"> {{ instrumento.instrumento }} </li>
  </ol>
</nav>
<div class="container mt-5">
  <div class="row">
    <div class="col-8">
      <img [src]="'http://localhost:8080/api/v1/instrumentos/images/' + instrumento.imagen" [alt]="instrumento.instrumento">
      <br />
      <small>{{ instrumento.descripcion }}</small>
    </div>
    <div class="col">
      <small class="text-muted">{{ instrumento.cantidadVendida }} vendidos</small>
      <h3>{{ instrumento.instrumento }}</h3>
      <h1 class="font-weight-light">{{ instrumento.precio | currency }}</h1>
      <small class="font-weight-bold">Marca: {{ instrumento.marca }}</small>
      <br />
      <small class="font-weight-bold">Modelo: {{ instrumento.modelo }}</small>
      <br />
      <br />
      <small>Costo Envio:</small>
      <app-shipping-cost [data]="instrumento.costoEnvio"></app-shipping-cost>
      <br />
      <button type="button" class="btn btn-outline-primary">Agregar al carrito</button>
    </div>
  </div>
</div>

// Trabajo Practico 5/trabajo-practico-5-react/src/pages/ProductDetails.js
import React, { Component } from "react";
import DataService from "../services/data.service";
import Toolbar from "../components/Toolbar";
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";
import Breadcrumb from 'react-bootstrap/Breadcrumb'
import ShippingCost from '../components/ShippingCost'

class ProductDetails extends Component {

  constructor() {
    super();
    this.state = { instrumento: {} };
  }

  componentDidMount() {
    this.getInstrumento(this.props.match.params.id);
  }

  getInstrumento(id) {
    DataService.getOne(id)
      .then((response) => {
        this.setState({
          instrumento: response.data,
        });
      })
      .catch((e) => {
        console.log(e);
      });
  }

  render() {
    const instrumento = this.state.instrumento;

    return (
      <React.Fragment>
        <Toolbar></Toolbar>
        <Breadcrumb>
          <Breadcrumb.Item href="/home">Home</Breadcrumb.Item>
          <Breadcrumb.Item href="/product-list">Productos</Breadcrumb.Item>
          <Breadcrumb.Item active>{instrumento.instrumento}</Breadcrumb.Item>
        </Breadcrumb>
        <Container className="container mt-5">
          <Row>
            <Col>
              <img
                src={`http://localhost:8080/api/v1/instrumentos/images/${instrumento.imagen}`}
                alt="Imagen producto"
                className="img-details"
              ></img>
              <div className="descripcion">
                <h5>Descipción</h5>
                <p>{instrumento.descripcion}</p>
              </div>
            </Col>
            <Col >
              <p className="sold">
                {instrumento.cantidadVendida} vendidos
              </p>
              <h3>{instrumento.instrumento}</h3>
              <h2 className="price-details">${instrumento.precio}</h2>
              <br></br>
              <h6 className="font-weight-bold">Marca: {instrumento.marca}</h6>
              <h6 className="font-weight-bold">Modelo: {instrumento.modelo}</h6>
              <p className="mt-5">Costo envío:</p>
              <ShippingCost costoEnvio={instrumento.costoEnvio}></ShippingCost>
              <br></br>
              <button className="btn btn-outline-primary">Agregar al carrito</button>
            </Col>
          </Row>
        </Container>
      </React.Fragment>
    );
  }
}

export default ProductDetails;
